version: '3.7'

# Simple application with a publicly available frontend connecting to a backend
# (frontend accessible at host's port 8080)

services: 
        frontend:
                build: .
                image: chaosecho/service:1
                environment:
                        BACKEND_SERVICES: "backend"
                        TIMEOUT: 100
                        PICK_PERCENTAGE: 100
                        FAIL_PERCENTAGE: 20
                depends_on:
                        - backend
                ports:
                        - "8080:80"
        backend:
                build: .
                image: chaosecho/service:1
                environment:
                        TIMEOUT: 1000
                        PICK_PERCENTAGE: 50
                        FAIL_PERCENTAGE: 20
