version: '3.8'

# Simple application with a publicly available frontend connecting to a backend
# (frontend accessible at host's port 8080)

services: 
        # ----------
        #  FRONTEND
        # ----------
        frontend:
                image: diunipisocc/chaosecho:1
                environment:
                        BACKEND_SERVICES: "backend"
                env_file:
                        - variables.env
                depends_on:
                        - backend
                ports:
                        - "8080:80"
        # ----------
        #  BACKEND
        # ----------
        backend:
                image: diunipisocc/chaosecho:1
                env_file:
                        - variables.env
                deploy:
                        replicas: 2
                        restart_policy:
                                        condition: any
                                        delay: 5s
